# Generated by Django 2.2.1 on 2019-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_id_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id_origem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
